# -*- coding: utf-8 -*-
"""FitMinds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rbTFP3INSbw89CqAlMAHs3ohyMLJJ--G
"""

# Install OpenAI library
!pip install openai gradio

!pip install --upgrade openai

!pip show openai

!pip install streamlit

!pip install streamlit pyngrok




import streamlit as st
import openai
from textblob import TextBlob
import pandas as pd

# Retrieve OpenAI API key from Streamlit Secrets
try:
    openai.api_key = st.secrets["OPENAI_API_KEY"]
except KeyError:
    st.error("API key is missing. Please set it in Streamlit Secrets.")

# --- GPT Response Generator ---
def generate_gpt_response(user_input):
    try:
        response = openai.ChatCompletion.create(
            model="gpt-3.5-turbo",
            messages=[
                {"role": "system", "content": "You are FitMinds, a friendly AI mental health assistant."},
                {"role": "user", "content": user_input}
            ]
        )
        return response['choices'][0]['message']['content']
    except Exception as e:
        return f"Error: {e}"

# --- Sentiment Analysis ---
def analyze_user_sentiment(text):
    sentiment_analysis = TextBlob(text)
    polarity = sentiment_analysis.sentiment.polarity
    if polarity > 0.5:
        return "Very Positive", polarity
    elif 0.1 < polarity <= 0.5:
        return "Positive", polarity
    elif -0.1 <= polarity <= 0.1:
        return "Neutral", polarity
    elif -0.5 < polarity < -0.1:
        return "Negative", polarity
    else:
        return "Very Negative", polarity

# --- Main Application ---
def main():
    st.title("FitMinds: AI Mental Health App")
    st.write("Share your thoughts and receive support and guidance!")

    if "chat_history" not in st.session_state:
        st.session_state["chat_history"] = []

    user_input = st.text_input("How are you feeling today?")
    if user_input:
        sentiment, polarity = analyze_user_sentiment(user_input)
        response = generate_gpt_response(user_input)

        # Save conversation
        st.session_state["chat_history"].append({"user": user_input, "bot": response, "sentiment": sentiment})

        st.markdown(f"**You:** {user_input}")
        st.markdown(f"**FitMinds:** {response}")
        st.markdown(f"**Sentiment:** {sentiment} (Polarity: {polarity})")

# Run the app
if __name__ == "__main__":
    main()

!pip install streamlit pyngrok

import streamlit as st

# App title and description
st.title("FitMinds: AI-Driven Mental Health App")
st.subheader("Welcome to FitMinds!")
st.write("This app provides mental health support for university students.")

# Input form
st.write("How are you feeling today?")
user_input = st.text_input("Share your thoughts or feelings:")

# Example response
if user_input:
    st.write(f"You entered: {user_input}")
    st.success("Stay positive! Here's a tip: Practice gratitude or take a short mindfulness break.")

